# Многостадийная сборка
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Копируем все файлы проектов и восстанавливаем зависимости
COPY PriceSentry.Beckend/*.sln .
COPY PriceSentry.Beckend/PriceSentry.WebApi/*.csproj ./PriceSentry.WebApi/
COPY PriceSentry.Beckend/PriceSentry.Application/*.csproj ./PriceSentry.Application/
COPY PriceSentry.Beckend/PriceSentry.Domain/*.csproj ./PriceSentry.Domain/
COPY PriceSentry.Beckend/Persistence/*.csproj ./PriceSentry.Persistence/
COPY PriceSentry.Beckend/TelegramBotHost/*.csproj ./TelegramBotHost/

RUN dotnet restore ./PriceSentry.WebApi/PriceSentry.WebApi.csproj

# Копируем весь остальной код и собираем
COPY PriceSentry.Beckend/ .
WORKDIR /src/PriceSentry.WebApi
RUN dotnet publish -c Release -o /app/publish

# Финальный образ
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Копируем собранное приложение
COPY --from=build /app/publish .
COPY .env /app/.env
# Создаём папку для SQLite (том будет примонтирован сюда)
RUN mkdir -p /app/data

# Переменные окружения по умолчанию (можно переопределить)
ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_URLS=http://+:80

ENTRYPOINT ["dotnet", "PriceSentry.WebApi.dll"]