# Этап сборки
FROM node:18-alpine AS build
WORKDIR /app
COPY PriceSentry.Frontend/package*.json ./
RUN npm ci
COPY PriceSentry.Frontend/ .
RUN npm run build

# Этап сервера
FROM nginx:alpine
# Копируем кастомный конфиг Nginx (опционально)
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Копируем собранную статику
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]